# Generated by Django 5.0 on 2023-12-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezume', '0002_resume_service_testomonial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testomonial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testomonial',
            name='desc',
        ),
        migrations.AddField(
            model_name='testomonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
