# Generated by Django 5.0 on 2023-12-21 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezume', '0005_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='created_at',
            new_name='start_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='created_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='education',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
