# Generated by Django 5.0 on 2023-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezume', '0006_rename_created_at_education_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
