# Generated by Django 5.0 on 2023-12-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezume', '0007_alter_education_end_at_alter_resume_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
